version: '3.8'
services:
  jpa-prpjects:
    image: postgres:15.3
    container_name: springboot-projects
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

  pgadmin-jpa:
    image: dpage/pgadmin4
    container_name: pg-jpa-projects
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}
    ports:
      - 5051:80